server:
  port: 9000
  servlet:
    context-path: /pay

spring:
  thymeleaf:
    cache: false
  application:
    name: micr-pay
  redis:
    port: 6379
    host: 192.168.239.133
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.lsp.pay
  consumer:
    check: false
    timeout: 60000
    retries: 0

