spring:
  application:
    name: micr-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: 192.168.239.133

server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: UTF-8
      force: true

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.lsp.web
  consumer:
    check: false
    timeout: 50000
    retries: 0
#京东万象（短息发送的接口）
jdwx:
  sms:
    url: https://way.jd.com/chuangxin/dxjk
    appkey: 3680fa919b771148da626bbcbd459475
    content: 【大富科技】你的验证码是：%s，3分钟内有效，请勿泄露给他人
    login-text: 【大富科技】登录验证码是：%s，3分钟内有效，请勿泄露给他人
  realname:
    url: https://way.jd.com/youhuoBeijing/test
    appkey: 3680fa919b771148da626bbcbd459475
jwt:
  secret: ce94f21d1e8e4c3197bee2ec7596e52b