spring:
  application:
    name: micr-task
dubbo:
  scan:
    base-packages: com.lsp.task
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 50000
    check: false
    retries: 0
server:
  port: 8081